behaviors:
  ArcadeDriver:
  #KartAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 2.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      memory_size: 256
      sequence_length: 64
      use_recurrent: false
      vis_encode_type: simple
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
    max_steps: 5.0e10
    time_horizon: 64
    summary_freq: 1000

# environment_parameters:
#   ArcadeDriver:
#       batch_size: 512
#       learning_rate: 2.0e-4
#   4x4Driver:
#       beta: 5.0e-4
#       batch_size: 512

#   MuscleDriver:
#       batch_size: 512

#   RoadsterDriver:
#       batch_size: 512
#       learning_rate: 2.0e-4
