behaviors:
  ArcadeDriver:
  #KartAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 2.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      memory_size: 256
      sequence_length: 64
      use_recurrent: false
      vis_encode_type: simple
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
    max_steps: 5.0e10
    time_horizon: 64
    summary_freq: 1000

# Details on https://github.com/Unity-Technologies/ml-agents/blob/release_18/docs/Training-Configuration-File.md#sac-specific-configurations

